live_config_reload = true

import = [
  # "~/.config/alacritty/themes/hardhacker.toml"
  #"~/.config/alacritty/themes/catppuccin-latte.toml"
  # "~/.config/alacritty/themes/catppuccin-frappe.toml"
  # "~/.config/alacritty/themes/catppuccin-macchiato.toml"
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[shell]
program = "/bin/fish"

[font]
normal = { family = "SFMono Nerd Font Mono", style = "Regular" }
size = 11

[window]
decorations = "none"
padding = { x = 16, y = 14 }
dynamic_padding = false
opacity = 0.90
